name: Deploy pre-prod
on:
  push:
    branches: [ dev ]
  
jobs:
  build:
    name: ssh/pull/build
    runs-on: ubuntu-latest
    steps:
    - name: Pull code & Build
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
         eval `ssh-agent -s`
         ssh-add ~/.ssh/${{ secrets.SSH_PUBLIC_KEY_NAME }}
         cd ${{ secrets.DEV_DIST }}
         git pull origin dev
         npm ci
         npm run build
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "Github Monitoring"
        DISCORD_AVATAR: "https://i.imgur.com/lPRYnJx.png"
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed successfully on https://beta.squadcalc.app'
