name: Deploy Prod
on:
  push:
    branches: [ master ]
  
jobs:
  build:
    name: ssh/pull/build
    runs-on: ubuntu-latest
    steps:
    - name: Pull code & Build
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
         eval `ssh-agent -s`
         ssh-add ~/.ssh/${{ secrets.SSH_PUBLIC_KEY_NAME }}
         cd ${{ secrets.DIST }}
         git pull origin master
         npm ci
         npm run build
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "Github bot"
        DISCORD_AVATAR: "https://i.imgur.com/lPRYnJx.png"
      uses: Ilshidur/action-discord@master
      with:
        args: |
          New version has been deployed on https://squadcalc.app !
          **Commit Link**: ${{ github.event.head_commit.url }}
          **Commit**: ${{ github.event.head_commit.message }}