name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
         cd ${{ secrets.DEV_DIST }}
    - name: pull code from github
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: dev
        token: ${{ github.token }}
